CREATE TABLESPACE APPDADOS
DATAFILE '+DATA/APPDADOS01.DBF'
SIZE 100M
EXTENT MANAGEMENT LOCAL
UNIFORM SIZE 128K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE APPINDEX
DATAFILE '+DATA/APPINDEX01.DBF'
SIZE 100M
EXTENT MANAGEMENT LOCAL
UNIFORM SIZE 128K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLE DEPARTAMENTO
(DEPTNUM NUMBER(10),
DNAME VARCHAR2(14 CHAR),
LOCAL VARCHAR2 (14 CHAR),
CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (DEPTNUM)
USING INDEX TABLESPACE APPINDEX)
TABLESPACE APPDADOS;


